// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Books            string
	Holds            string
	OverdueCheckouts string
	Patrons          string
}{
	Books:            "books",
	Holds:            "holds",
	OverdueCheckouts: "overdue_checkouts",
	Patrons:          "patrons",
}
