// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Books", testBooksUpsert)

	t.Run("Holds", testHoldsUpsert)

	t.Run("OverdueCheckouts", testOverdueCheckoutsUpsert)

	t.Run("Patrons", testPatronsUpsert)
}
