// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package main

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BookType.
const (
	Circulating BookType = "Circulating"
	Restricted  BookType = "Restricted"
)

// BookType defines model for BookType.
type BookType string

// CreateABookJSONBody defines parameters for CreateABook.
type CreateABookJSONBody struct {
	Author string `json:"author"`
	Isbn   string `json:"isbn"`
	Title  string `json:"title"`
}

// CreateABookInstanceJSONBody defines parameters for CreateABookInstance.
type CreateABookInstanceJSONBody struct {
	BookType BookType `json:"bookType"`
	PlacedAt string   `json:"placedAt"`
}

// CreateABookJSONRequestBody defines body for CreateABook for application/json ContentType.
type CreateABookJSONRequestBody CreateABookJSONBody

// CreateABookInstanceJSONRequestBody defines body for CreateABookInstance for application/json ContentType.
type CreateABookInstanceJSONRequestBody CreateABookInstanceJSONBody
