// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package ports

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// CheckoutJSONBody defines parameters for Checkout.
type CheckoutJSONBody struct {
	BookId string `json:"bookId"`
}

// CancelHoldJSONBody defines parameters for CancelHold.
type CancelHoldJSONBody struct {
	BookId string `json:"bookId"`
}

// PlaceHoldJSONBody defines parameters for PlaceHold.
type PlaceHoldJSONBody struct {
	BookId    string `json:"bookId"`
	NumOfDays int    `json:"numOfDays"`
}

// CheckoutJSONRequestBody defines body for Checkout for application/json ContentType.
type CheckoutJSONRequestBody CheckoutJSONBody

// CancelHoldJSONRequestBody defines body for CancelHold for application/json ContentType.
type CancelHoldJSONRequestBody CancelHoldJSONBody

// PlaceHoldJSONRequestBody defines body for PlaceHold for application/json ContentType.
type PlaceHoldJSONRequestBody PlaceHoldJSONBody
